//displaying alert message after validations
export const SHOW_ALERT = "DISPLAY_ALERT";

//action to clear the Alert message when the conditions are satisfied
export const HIDE_ALERT = "HIDE_ALERT";

//Actions for user registeration page
export const USER_REGISTER_START = "USER_REGISTER_START";
export const USER_REGISTER_SUCCESSFUL = "USER_REGISTER_SUCCESSFUL";
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR"; 

//ACTION for user login page
export const USER_LOGIN_START = "USER_LOGIN_START";
export const USER_LOGIN_SUCCESSFUL = "USER_LOGIN_SUCCESSFUL";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

//ACTION To CHANGE PAGE

export const CHANGE_PAGE="CHANGE_PAGE";


//Actions for Update User Page
export const USER_UPDATE_START = "USER_UPDATE_START";
export const USER_UPDATE_SUCCESSFULL = "USER_UPDATE_SUCCESSFULL";
export const USER_UPDATE_ERROR = "USER_UPDATE_ERROR";

export const SET_USER_PROFILE = "SET_USER_PROFILE";

//ADD EXPENDITURE
export const ADD_EXPENDITURE_START = "ADD_EXPENDITURE_START";
export const ADD_EXPENDITURE_SUCCESSFULL = "ADD_EXPENDITURE_SUCCESSFULL";
export const ADD_EXPENDITURE_ERROR = "ADD_EXPENDITURE_ERROR";

//ADD & GET GRADES
export const GET_ALL_GRADES_ERROR = "GET_ALL_GRADES_ERROR";
export const GET_ALL_GRADES_START = "GET_ALL_GRADES_START";
export const GET_ALL_GRADES_SUCCESSFULL = "GET_ALL_GRADES_SUCCESSFULL";
export const SET_GRADES_ERROR = "SET_GRADES_ERROR";
export const SET_GRADES_START = "SET_GRADES_START";
export const SET_GRADES_SUCCESSFULL = "SET_GRADES_SUCCESSFULL";

//ADD & GET EXPENSES
export const GET_ALL_EXPENDITURE_ERROR = "GET_ALL_EXPENDITURE_ERROR";
export const GET_ALL_EXPENDITURE_START = "GET_ALL_EXPENDITURE_START";
export const GET_ALL_EXPENDITURE_SUCCESSFULL = "GET_ALL_EXPENDITURE_SUCCESSFULL";

export const GET_ALL_JOBS_ERROR = "GET_ALL_JOBS_ERROR";
export const GET_ALL_JOBS_START = "GET_ALL_JOBS_START";
export const GET_ALL_JOBS_SUCCESSFULL = "GET_ALL_JOBS_SUCCESSFULL";

export const ADD_JOB_START = "ADD_JOB_START";
export const ADD_JOB_SUCCESSFULL = "ADD_JOB_SUCCESSFULL";
export const ADD_JOB_ERROR = "ADD_JOB_ERROR";

export const USER_LOGOUT = "USER_LOGOUT";

export const VALUES_CLEAR = "VALUES_CLEAR";

export const SET_JOB_EDIT = "SET_JOB_EDIT";
export const SET_EXPENSE_EDIT = "SET_EXPENSE_EDIT";
export const SET_GRADE_EDIT = "SET_GRADE_EDIT";


export const JOB_EDIT_SUCCESSFULL = "JOB_EDIT_SUCCESSFULL";
export const JOB_EDIT_START = "JOB_EDIT_START";
export const JOB_EDIT_ERROR = "JOB_EDIT_ERROR";

export const JOB_DELETE_BEGIN = "JOB_DELETE_BEGIN";
export const JOB_DELETE_COMPLETE = "JOB_DELETE_COMPLETE";

export const EXPENSE_EDIT_SUCCESSFULL = "EXPENSE_EDIT_SUCCESSFULL";
export const EXPENSE_EDIT_START = "EXPENSE_EDIT_START";
export const EXPENSE_EDIT_ERROR = "EXPENSE_EDIT_ERROR";

export const EXPENSE_DELETE_BEGIN = "EXPENSE_DELETE_BEGIN";
export const EXPENSE_DELETE_COMPLETE = "EXPENSE_DELETE_COMPLETE";

export const GRADE_EDIT_SUCCESSFULL = "GRADE_EDIT_SUCCESSFULL";
export const GRADE_EDIT_START = "GRADE_EDIT_START";
export const GRADE_EDIT_ERROR = "GRADE_EDIT_ERROR";

export const GRADE_DELETE_BEGIN = "GRADE_DELETE_BEGIN";
export const GRADE_DELETE_COMPLETE = "GRADE_DELETE_COMPLETE";


